spring.application.name=pharmacy-service

server.port=8081

# Kafka configuration
kafka.bootstrap-servers=localhost:9092

#Kafka producer configuration
kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
kafka.producer.spring.json.add.type.headers=false